# MAINTAINED BY BERRABE
# https://github.com/berrabe/docker-reverse-proxy
---
version: "2.2"

x-resource: &resource
    restart: unless-stopped
    cpus: 1
    mem_limit: 300M
    memswap_limit: 300M


services:
    reverse-proxy:
        << : *resource
        image: jwilder/nginx-proxy:alpine
        container_name: reverse-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./reverse-proxy/cert:/etc/nginx/certs
            - ./reverse-proxy/vhost.d:/etc/nginx/vhost.d
            - ./reverse-proxy/html:/usr/share/nginx/html
            - ./reverse-proxy/dhparam:/etc/nginx/dhparam
            - ./conf/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
        ports:
            - "80:80"
            - "443:443"
        environment:
            HTTPS_METHOD: noredirect
            DEFAULT_HOST: example.com

    reverse-proxy-letsencrypt:
        << : *resource
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: reverse-proxy-letencrypt
        volumes_from:
            - reverse-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./reverse-proxy/acme:/etc/acme.sh
        environment:        
            DEFAULT_EMAIL: xxx@example.com
        depends_on:
            - reverse-proxy


# Useful for connect betwwen docker container without auto_net.brb
# genereate your custom network with 'docker network create <name>'

# networks:
#     default:
#         external:
#             name: <your custom network name>